### ISSUE TITLE
Error during bot initialization

### ISSUE THREAD

**Issue by martinodutto** [carlopantaleo/SunriseSunsetBot#1]
When I create a new conversation with the bot, I immediately get the following error message:

![issue_1](https://user-images.githubusercontent.com/19760477/28719518-778d3078-73aa-11e7-920f-d55db425cda3.PNG)

I don't have any option on the command list, and whenever I send any message to the bot, this is what I get:

![issue_2](https://user-images.githubusercontent.com/19760477/28719613-d51744a4-73aa-11e7-80c8-838f830f52dd.PNG)

Can you please check the problem?

Thank you very much in advance.

**MD** ;)

**Comment by carlopantaleo** [comment]
Issue resolved with release v1.1.2.
