### ISSUE TITLE
Unclear location formatting

### ISSUE THREAD

**Issue by martinodutto** [carlopantaleo/SunriseSunsetBot#2]
Would be great if you could add some hint to the "Please send me your location" request.

![issue_3](https://user-images.githubusercontent.com/19760477/28732456-3dedbf76-73d8-11e7-9de3-0e1b99e068f3.PNG)

How should I format my desired location? Which coordinates system may I use? Is there a fast way to send my location from, e.g., my phone?

Thank you.

**MD**

**Comment by carlopantaleo** [comment]
At the moment you should send your location not as a simple text message, but as a "location" message (using send -> location in your mobile app). I'm not sure this functionality is available for desktop clients.

I'm not going to close this issue until I'll add the possibility to send the location also as a simple text message.

**Comment by carlopantaleo** [comment]
Sending the location is now more straight-forward.
